name: myfirstworkflow
on: workflow_dispatch
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - name: myfirstcommand
     run:  sleep 10s
 Deploy123:
  needs: Build 
  runs-on: ubuntu-latest
  steps:
   - name: myfirstcommand
     run:  echo "first deploy"    