name: myfirstworkflow
on: workflow_dispatch
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - name: myfirstcommand
     run:  echo "first build"
 Deploy:
  runs-on: ubuntu-latest
  steps:
   - name: myfirstcommand
     run:  echo "first deploy"    