name: myfirstworkflow
on:
 push: 
 pull_request:
  types: 
   - opened
   - closed 
  branches:
   - production     
 workflow_dispatch:    
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - name: myfirstcommand
     run:  sleep 10s
 Deploy12345689123:
  needs: Build 
  runs-on: ubuntu-latest
  steps:
   - name: myfirstcommand
     run:  echo "first deploy"    