name: myfirstworkflow
on: push
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - name: myfirstcommand
     run:  sleep 10s
 Deploy1234:
  needs: Build 
  runs-on: ubuntu-latest
  steps:
   - name: myfirstcommand
     run:  echo "first deploy"    